my:
 greeting: Hello World from config server  - qa enviornment
 
db:
 connection: connection-string-here-from-config-server-qa-enviornment
 host: 127.0.0.2
 port: 1201
 
api:
 key: cea3b7a0b210db1ea9f3707365849dd8
